"""Self-contained geography lookup (no external dependency).

Maps the ISO-2 country codes found in the OpenAlex `countries` column to a
display name, ISO-3 code (needed by Plotly choropleths), a continent/region
bucket (used by the Region filter), and an approximate population in millions
(used by the "papers per million" map metric).

Population figures are ~2023 estimates rounded to the nearest million and are
only provided for countries with meaningful research output; missing values
fall back to ``None`` and are simply excluded from the per-million view.
"""

# iso2 -> (name, iso3, region, population_millions_or_None)
_COUNTRIES = {
    "AE": ("United Arab Emirates", "ARE", "Asia", 9.4),
    "AG": ("Antigua and Barbuda", "ATG", "North America", None),
    "AL": ("Albania", "ALB", "Europe", 2.8),
    "AM": ("Armenia", "ARM", "Asia", 2.8),
    "AR": ("Argentina", "ARG", "South America", 45.8),
    "AT": ("Austria", "AUT", "Europe", 9.0),
    "AU": ("Australia", "AUS", "Oceania", 26.0),
    "AZ": ("Azerbaijan", "AZE", "Asia", 10.1),
    "BA": ("Bosnia and Herzegovina", "BIH", "Europe", 3.2),
    "BB": ("Barbados", "BRB", "North America", None),
    "BD": ("Bangladesh", "BGD", "Asia", 172.0),
    "BE": ("Belgium", "BEL", "Europe", 11.7),
    "BF": ("Burkina Faso", "BFA", "Africa", 22.7),
    "BG": ("Bulgaria", "BGR", "Europe", 6.4),
    "BH": ("Bahrain", "BHR", "Asia", 1.5),
    "BI": ("Burundi", "BDI", "Africa", 12.9),
    "BJ": ("Benin", "BEN", "Africa", 13.0),
    "BM": ("Bermuda", "BMU", "North America", None),
    "BN": ("Brunei", "BRN", "Asia", 0.4),
    "BO": ("Bolivia", "BOL", "South America", 12.2),
    "BR": ("Brazil", "BRA", "South America", 216.0),
    "BS": ("Bahamas", "BHS", "North America", 0.4),
    "BW": ("Botswana", "BWA", "Africa", 2.7),
    "BY": ("Belarus", "BLR", "Europe", 9.2),
    "CA": ("Canada", "CAN", "North America", 40.0),
    "CG": ("Congo", "COG", "Africa", 6.1),
    "CH": ("Switzerland", "CHE", "Europe", 8.8),
    "CI": ("Cote d'Ivoire", "CIV", "Africa", 28.2),
    "CL": ("Chile", "CHL", "South America", 19.6),
    "CM": ("Cameroon", "CMR", "Africa", 28.6),
    "CN": ("China", "CHN", "Asia", 1412.0),
    "CO": ("Colombia", "COL", "South America", 52.0),
    "CR": ("Costa Rica", "CRI", "North America", 5.2),
    "CU": ("Cuba", "CUB", "North America", 11.2),
    "CY": ("Cyprus", "CYP", "Europe", 1.3),
    "CZ": ("Czechia", "CZE", "Europe", 10.5),
    "DE": ("Germany", "DEU", "Europe", 84.0),
    "DK": ("Denmark", "DNK", "Europe", 5.9),
    "DO": ("Dominican Republic", "DOM", "North America", 11.2),
    "DZ": ("Algeria", "DZA", "Africa", 45.6),
    "EC": ("Ecuador", "ECU", "South America", 18.2),
    "EE": ("Estonia", "EST", "Europe", 1.4),
    "EG": ("Egypt", "EGY", "Africa", 112.0),
    "ES": ("Spain", "ESP", "Europe", 48.4),
    "ET": ("Ethiopia", "ETH", "Africa", 126.0),
    "FI": ("Finland", "FIN", "Europe", 5.6),
    "FJ": ("Fiji", "FJI", "Oceania", 0.9),
    "FR": ("France", "FRA", "Europe", 68.0),
    "GA": ("Gabon", "GAB", "Africa", 2.4),
    "GB": ("United Kingdom", "GBR", "Europe", 67.0),
    "GE": ("Georgia", "GEO", "Asia", 3.7),
    "GF": ("French Guiana", "GUF", "South America", None),
    "GH": ("Ghana", "GHA", "Africa", 34.1),
    "GL": ("Greenland", "GRL", "North America", None),
    "GM": ("Gambia", "GMB", "Africa", 2.7),
    "GR": ("Greece", "GRC", "Europe", 10.4),
    "GT": ("Guatemala", "GTM", "North America", 17.6),
    "GY": ("Guyana", "GUY", "South America", 0.8),
    "HK": ("Hong Kong", "HKG", "Asia", 7.5),
    "HR": ("Croatia", "HRV", "Europe", 3.9),
    "HU": ("Hungary", "HUN", "Europe", 9.6),
    "ID": ("Indonesia", "IDN", "Asia", 277.0),
    "IE": ("Ireland", "IRL", "Europe", 5.1),
    "IL": ("Israel", "ISR", "Asia", 9.7),
    "IM": ("Isle of Man", "IMN", "Europe", None),
    "IN": ("India", "IND", "Asia", 1428.0),
    "IQ": ("Iraq", "IRQ", "Asia", 45.5),
    "IR": ("Iran", "IRN", "Asia", 89.2),
    "IS": ("Iceland", "ISL", "Europe", 0.4),
    "IT": ("Italy", "ITA", "Europe", 58.9),
    "JM": ("Jamaica", "JAM", "North America", 2.8),
    "JO": ("Jordan", "JOR", "Asia", 11.3),
    "JP": ("Japan", "JPN", "Asia", 125.0),
    "KE": ("Kenya", "KEN", "Africa", 55.1),
    "KG": ("Kyrgyzstan", "KGZ", "Asia", 6.7),
    "KH": ("Cambodia", "KHM", "Asia", 16.9),
    "KR": ("South Korea", "KOR", "Asia", 51.7),
    "KW": ("Kuwait", "KWT", "Asia", 4.3),
    "KY": ("Cayman Islands", "CYM", "North America", None),
    "KZ": ("Kazakhstan", "KAZ", "Asia", 19.6),
    "LB": ("Lebanon", "LBN", "Asia", 5.5),
    "LI": ("Liechtenstein", "LIE", "Europe", None),
    "LK": ("Sri Lanka", "LKA", "Asia", 22.2),
    "LS": ("Lesotho", "LSO", "Africa", 2.3),
    "LT": ("Lithuania", "LTU", "Europe", 2.9),
    "LU": ("Luxembourg", "LUX", "Europe", 0.7),
    "LV": ("Latvia", "LVA", "Europe", 1.9),
    "LY": ("Libya", "LBY", "Africa", 6.9),
    "MA": ("Morocco", "MAR", "Africa", 37.5),
    "MC": ("Monaco", "MCO", "Europe", None),
    "MD": ("Moldova", "MDA", "Europe", 2.5),
    "ME": ("Montenegro", "MNE", "Europe", 0.6),
    "MG": ("Madagascar", "MDG", "Africa", 30.3),
    "MK": ("North Macedonia", "MKD", "Europe", 2.1),
    "ML": ("Mali", "MLI", "Africa", 23.3),
    "MM": ("Myanmar", "MMR", "Asia", 54.6),
    "MN": ("Mongolia", "MNG", "Asia", 3.4),
    "MO": ("Macao", "MAC", "Asia", 0.7),
    "MT": ("Malta", "MLT", "Europe", 0.5),
    "MU": ("Mauritius", "MUS", "Africa", 1.3),
    "MV": ("Maldives", "MDV", "Asia", 0.5),
    "MW": ("Malawi", "MWI", "Africa", 20.4),
    "MX": ("Mexico", "MEX", "North America", 128.0),
    "MY": ("Malaysia", "MYS", "Asia", 33.9),
    "NA": ("Namibia", "NAM", "Africa", 2.6),
    "NC": ("New Caledonia", "NCL", "Oceania", None),
    "NG": ("Nigeria", "NGA", "Africa", 223.0),
    "NI": ("Nicaragua", "NIC", "North America", 7.0),
    "NL": ("Netherlands", "NLD", "Europe", 17.8),
    "NO": ("Norway", "NOR", "Europe", 5.5),
    "NP": ("Nepal", "NPL", "Asia", 30.9),
    "NZ": ("New Zealand", "NZL", "Oceania", 5.2),
    "OM": ("Oman", "OMN", "Asia", 4.6),
    "PA": ("Panama", "PAN", "North America", 4.5),
    "PE": ("Peru", "PER", "South America", 34.0),
    "PH": ("Philippines", "PHL", "Asia", 117.0),
    "PK": ("Pakistan", "PAK", "Asia", 240.0),
    "PL": ("Poland", "POL", "Europe", 37.7),
    "PR": ("Puerto Rico", "PRI", "North America", 3.2),
    "PS": ("Palestine", "PSE", "Asia", 5.4),
    "PT": ("Portugal", "PRT", "Europe", 10.4),
    "PY": ("Paraguay", "PRY", "South America", 6.9),
    "QA": ("Qatar", "QAT", "Asia", 2.7),
    "RE": ("Reunion", "REU", "Africa", None),
    "RO": ("Romania", "ROU", "Europe", 19.0),
    "RS": ("Serbia", "SRB", "Europe", 6.6),
    "RU": ("Russia", "RUS", "Europe", 144.0),
    "RW": ("Rwanda", "RWA", "Africa", 14.0),
    "SA": ("Saudi Arabia", "SAU", "Asia", 36.9),
    "SD": ("Sudan", "SDN", "Africa", 48.1),
    "SE": ("Sweden", "SWE", "Europe", 10.5),
    "SG": ("Singapore", "SGP", "Asia", 5.9),
    "SI": ("Slovenia", "SVN", "Europe", 2.1),
    "SK": ("Slovakia", "SVK", "Europe", 5.4),
    "SL": ("Sierra Leone", "SLE", "Africa", 8.6),
    "SN": ("Senegal", "SEN", "Africa", 17.7),
    "SO": ("Somalia", "SOM", "Africa", 18.1),
    "SR": ("Suriname", "SUR", "South America", 0.6),
    "SS": ("South Sudan", "SSD", "Africa", 11.1),
    "SY": ("Syria", "SYR", "Asia", 23.2),
    "SZ": ("Eswatini", "SWZ", "Africa", 1.2),
    "TH": ("Thailand", "THA", "Asia", 71.8),
    "TJ": ("Tajikistan", "TJK", "Asia", 10.1),
    "TN": ("Tunisia", "TUN", "Africa", 12.5),
    "TR": ("Turkey", "TUR", "Asia", 85.3),
    "TT": ("Trinidad and Tobago", "TTO", "North America", 1.5),
    "TW": ("Taiwan", "TWN", "Asia", 23.4),
    "TZ": ("Tanzania", "TZA", "Africa", 67.4),
    "UA": ("Ukraine", "UKR", "Europe", 36.7),
    "UG": ("Uganda", "UGA", "Africa", 48.6),
    "US": ("United States", "USA", "North America", 335.0),
    "UY": ("Uruguay", "URY", "South America", 3.4),
    "UZ": ("Uzbekistan", "UZB", "Asia", 35.6),
    "VE": ("Venezuela", "VEN", "South America", 28.3),
    "VN": ("Vietnam", "VNM", "Asia", 98.9),
    "XK": ("Kosovo", "XKX", "Europe", 1.6),
    "YE": ("Yemen", "YEM", "Asia", 34.4),
    "ZA": ("South Africa", "ZAF", "Africa", 60.4),
    "ZM": ("Zambia", "ZMB", "Africa", 20.6),
    "ZW": ("Zimbabwe", "ZWE", "Africa", 16.7),
}

REGIONS = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"]


def name(iso2: str):
    rec = _COUNTRIES.get(iso2)
    return rec[0] if rec else iso2


def iso3(iso2: str):
    rec = _COUNTRIES.get(iso2)
    return rec[1] if rec else None


def region(iso2: str):
    rec = _COUNTRIES.get(iso2)
    return rec[2] if rec else "Other"


def population_m(iso2: str):
    rec = _COUNTRIES.get(iso2)
    return rec[3] if rec else None
